### ISSUE TITLE
Release des Gems auf GitHub oder GitLab

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vcoworkflows-ruby2#3]

**Comment by phortx** [comment]
Das Repo ist öffentlich, das heißt in der Gemfile kann das gem via

```ruby
gem 'vcoworkflows', github: github: 'wintermeyer/vcoworkflows-ruby2'
```

eingebunden und dann via `bundle update vcoworkflows` installiert werden.

**Comment by phortx** [comment]
Habe die `.gem` file zusätzlich ins Repo gepusht: https://github.com/wintermeyer/vcoworkflows-ruby2/blob/master/vcoworkflows-0.2.3.gem
