### ISSUE TITLE
Clean up README buttons

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vcoworkflows-ruby2#4]
<img width="482" alt="Bildschirmfoto 2019-06-04 um 18 53 20" src="https://user-images.githubusercontent.com/69770/58898101-16901c80-86fa-11e9-8c41-95c3ad68ed5a.png">

Clean up what what is used and what not. If in doubt: Delete.

**Comment by wintermeyer** [comment]
Isn't there a 2 missing?

<img width="849" alt="Bildschirmfoto 2019-06-05 um 16 17 50" src="https://user-images.githubusercontent.com/69770/58963600-c5d9fb80-87ad-11e9-878c-68ab046a36ad.png">

**Comment by phortx** [comment]
Oops ... Fixed :)
